services:
  - type: static_site
    name: om-satarkar-store-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://e-commerce-webapplication-1.onrender.com

  - type: web
    name: om-satarkar-store-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://e-commerce-webapplication-zoyj.onrender.com
      - key: ADMIN_NAME
        value: Om Satarkar
      - key: ADMIN_LOGIN
        value: om
      - key: ADMIN_EMAIL
        value: admin@omsatarkar.store
      - key: ADMIN_PASSWORD
        sync: false
